name:                json-and-more
version:             0.1.0.0
github:              "DJMiky007/json-and-more"
license:             none
author:              "já"
maintainer:          "já"
copyright:           "2021 já"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json-and-more#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- unordered-containers
- parsec
- megaparsec
- scientific
- aeson

library:
  source-dirs: src

executables:
  json-and-more-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-and-more

tests:
  json-and-more-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-and-more
